repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
        exclude: '^(test_|debug_|analyze_|setup_|create_|release-)'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]
        exclude: '^(test_|debug_|analyze_|setup_|create_|release-)'

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.10
    hooks:
      - id: pylint
        args: [
          --max-line-length=88,
          --disable=import-error,too-many-locals,too-many-branches,too-many-statements,too-many-arguments,too-many-return-statements,unused-argument,no-else-return,too-many-positional-arguments,too-many-nested-blocks
        ]
        files: ^custom_components/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, homeassistant]
        files: '^custom_components/'
