name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

        Before submitting, please:
        1. Search existing issues to avoid duplicates
        2. Check if the feature aligns with the project goals
        3. Consider if this could be implemented as a separate integration

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (configuration option, UI change)
        - Medium (new sensor type, API enhancement)
        - High (major architectural change, new integration patterns)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Areas
      description: Which parts of the integration would this feature affect?
      options:
        - label: API connectivity
        - label: Sensor entities
        - label: Binary sensor entities
        - label: Configuration flow
        - label: User interface
        - label: Documentation
        - label: Error handling

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to help document this feature
